# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-12 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181012_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
